ISSUE-1344: Add missing classname argument in download-streamine-artifacts.py
While trying to run download-streamine-artifacts.py, it throws below error.

Unrecognized option: --artifactRepositories
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

It appears that the classname is missing in the java command that the script is trying to execute

#fixes #1344

Author: Arun Mahadevan <arunm@apache.org>

Closes #1343 from arunmahadevan/fix-script