STREAMLINE-616: Fix sum aggregate function
Right now Sum throws exception
"2016-12-23 10:04:34.970 o.a.s.s.r.p.RuleProcessorRuntime [ERROR] Error evaluating rule processor with id: 2.1, error: java.lang.Long cannot be cast to [Ljava.lang.Object;
java.lang.ClassCastException: java.lang.Long cannot be cast to [Ljava.lang.Object;
at org.apache.storm.sql.generated.Processor$4.dataReceived(Processor.java:112) ~[?:?]"

Calcite code converter inserts a cast to Object[] when the return type of the function cannot be directly mapped to Sql type. Switch to Storm's builtin aggregate function